name: Bump package version

on:
  workflow_dispatch:
    inputs:
      changes:
        description: "Level of changes"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-package-version:
    outputs:
      tag: ${{ steps.bump-package-version.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      - name: Bump package version
        id: bump-package-version
        run: |
          echo "tag=$(npm version ${{ inputs.changes }})" >> $GITHUB_OUTPUT
          git push --tags
          git push origin main

  publish-package:
    needs: bump-package-version
    uses: ./.github/workflows/public-package.yaml
    with:
      tag: ${{ needs.bump-package-version.outputs.tag }}
    secrets: inherit
